"""UI copy labels used by Magnetism Scanner templates."""

_MAGNETISM_UI = {
    "en": {
        "language": "Language",
        "other_lang": "ES",
        "scanner_title": "Brand3 Scanner",
        "scanner_tag": "competitive analysis and 7-layer audit",
        "manual_summary": "Manual text block input (legacy/debug, not comparable)",
        "manual_label": "Raw website content / landing page copy:",
        "manual_placeholder": "Paste website homepage text copy here...",
        "manual_note": (
            "Manual input bypasses Brand Audit acquisition and is marked as legacy direct evidence. Use it "
            "only for debugging or ad-hoc review; production/comparable scans should use URL or an existing "
            "Brand Audit run."
        ),
        "from_audit": "from_brand_audit",
        "from_audit_tag": "reuse existing evidence packet",
        "from_audit_intro": (
            "Canonical path: generate Magnetism from an existing Brand Audit run. URL scans above create the "
            "same kind of Brand Audit snapshot first; this table simply reuses one that already exists."
        ),
        "use_evidence": "use evidence",
        "evidence_vnext_diag": "vNext evidence",
        "evidence_vnext_json": "raw JSON",
        "no_audits": "// no Brand Audit runs available yet — run a URL scan above or create a normal audit first.",
        "recent_scans": "recent_scans",
        "latest_runs": "latest runs",
        "view_sheet": "view sheet",
        "audit_score": "audit score",
        "no_scans": "// no magnetism scans recorded yet — run the first scan above.",
        "date": "date",
        "brand": "brand",
        "score": "score",
        "coherence": "coherence",
        "quadrant": "positioning quadrant",
        "url": "url",
        "run": "run",
        "result": "result",
        "back": "Back to Brand3 Scanner",
        "home": "Home",
        "recent_scans_nav": "Recent scans",
        "new_scan": "New scan",
        "sv9_shadow": "SV9 shadow",
        "ranking": "Ranking",
        "tools": "tools",
        "scanner_history_intro": "Review previous scanner results and open their SV9 score, evidence, audit and methodology.",
        "base_reading": "Base reading",
        "research_evidence": "Research Evidence",
        "audit": "Audit",
        "audit_tag": "Brand Audit inside the scanner result",
        "audit_intro": "Executive Brand Audit reading attached to this scanner result.",
        "audit_unavailable": "No Brand Audit snapshot is attached to this scan.",
        "audit_run": "Brand Audit run",
        "executive_summary": "Executive summary",
        "primary_risk": "Primary risk",
        "primary_opportunity": "Primary opportunity",
        "internal_audit": "Internal score audit",
        "internal_audit_tag": "score provenance and TLDR v2",
        "audit_status": "Audit status",
        "score_integrity": "Score integrity",
        "score_summary": "Score summary",
        "computed_score": "Computed score",
        "reviewed_score": "Reviewed score",
        "display_score": "Display score",
        "display_score_source": "Display source",
        "display_score_status": "Display status",
        "dimension_breakdown": "Dimension breakdown",
        "confidence_summary": "Confidence summary",
        "fallback_flags": "Fallback flags",
        "rules_caps": "Rules / caps",
        "warnings": "Warnings",
        "recommended_action": "Recommended action",
        "tldr_v2_internal_summary": "TLDR v2 internal summary",
        "fingerprint_details": "Fingerprint details",
        "raw_feature_provenance": "Raw feature provenance",
        "reviewed_score_block": "Reviewed score block",
        "dimension_audit": "Dimension audit",
        "findings": "Findings",
        "recommendation": "Recommendation",
        "confidence": "Confidence",
        "legacy_audit": "Legacy audit fallback",
        "evidence_reliability": "Evidence Reliability",
        "evidence": "Evidence",
        "evidence_basis": "Evidence basis",
        "total_evidence": "Total evidence",
        "overall_status": "Overall status",
        "report_mode": "Report mode",
        "dimension_names": {
            "coherencia": "Coherence",
            "presencia": "Presence",
            "percepcion": "Perception",
            "diferenciacion": "Differentiation",
            "vitalidad": "Vitality",
        },
        "methodology_details": "Methodology Details",
        "methodology": "Methodology",
        "moodboard": "Moodboard",
        "moodboard_tag": "visual board built from captured brand assets",
        "moodboard_intro": (
            "Representative images the brand publishes on its owned surfaces, captured during this scan and "
            "arranged as a moodboard next to the strategic reading."
        ),
        "moodboard_hint": "drag images to rearrange",
        "moodboard_shuffle": "shuffle",
        "moodboard_empty": (
            "No representative images were captured for this scan. The moodboard needs a Brand Audit run "
            "with a persisted web acquisition."
        ),
        "moodboard_visual_reading": "Visual reading",
        "moodboard_visual_reading_tag": "strategic blocks that frame the imagery",
        "moodboard_inventory": "Image inventory",
        "moodboard_inventory_tag": "captured assets and their roles",
        "moodboard_role": "role",
        "moodboard_alt": "alt text",
        "moodboard_roles": {
            "logo": "logo / icon",
            "social_card": "social card",
            "content": "page image",
        },
        "moodboard_source_note": (
            "Images are linked directly from the brand's own pages as captured at scan time; an empty slot "
            "means the asset is no longer reachable."
        ),
        "detail_tag": "9 strategic blocks derived from 7 Magenta signals",
        "no_detected": "(not detected)",
        "system_reading": "TLDR System Reading",
        "system_reading_tag": "tensions and validation questions inside TLDR Brand3",
        "client_tldr_v2": "Client TLDR v2",
        "client_tldr_v2_tag": "score-aware client preview",
        "generate_sv9": "Generate SV9",
        "sv9_generation_status": "SV9 generation",
        "sv9_generation_tag": "shadow scan materialization",
        "sv9_generation_intro": "Generating the shadow V9 scan from the persisted Brand Audit snapshot.",
        "sv9_generation_queued": "waiting to materialize the shadow scan",
        "sv9_generation_ready": "shadow scan ready ...",
        "sv9_generation_ready_link": "→ open SV9 scan",
        "sv9_generation_back": "← back to scan",
        "score_reading": "Score reading",
        "score_status": "Score status",
        "score_note": "Score note",
        "evidence_refs": "Evidence refs",
        "tldr_block_names": {
            "core_purpose": "CORE PURPOSE",
            "magnetism": "MAGNETISM",
            "value_proposition": "VALUE PROPOSITION",
            "personality": "PERSONALITY",
            "brand_idea": "BRAND IDEA",
            "attributes": "ATTRIBUTES",
            "values": "VALUES",
            "mission": "MISSION",
            "vision": "VISION",
        },
        "credibility_support": "Credibility support",
        "strategic_tensions": "Strategic tensions",
        "validation_questions": "Validation questions",
        "diagnosis": "diagnosis",
        "diagnosis_tag": "bounded by observed and missing signals",
        "limitations": "limitations",
        "research_intro": "Evidence graph and Research Pack used to produce the TLDR Brand3 reading.",
        "research_tag": "research evidence",
        "evidence_reliability_intro": (
            "Objective diagnostic for the Research Pack used as TLDR input. It evaluates evidence quality, "
            "not the brand, and does not change the TLDR blocks."
        ),
        "evidence_reliability_tag": "input quality, not brand quality",
        "quality_status": "Status",
        "quality_score": "Score",
        "quality_gate": "Gate",
        "quality_dimensions": "Quality dimensions",
        "quality_dimensions_tag": "offer, audience, proof, traceability, and noise",
        "quality_warnings": "Warnings",
        "quality_failures": "Gate failures",
        "quality_pack_summary": "Pack summary",
        "quality_missing": "No Research Pack quality diagnostic was persisted for this scan.",
        "no_quality_warnings": "No warnings persisted.",
        "no_quality_failures": "No gate failures.",
        "pack_source": "Pack Source",
        "tldr_mode": "TLDR Mode",
        "evidence_vnext_contract": "vNext Evidence Contract",
        "evidence_vnext_contract_tag": "promotion readiness and source hygiene",
        "evidence_vnext_contract_intro": (
            "Operational summary of the vNext evidence gate for this attached Brand Audit run. It shows "
            "what can safely feed the Research Pack and what stayed in review or noise."
        ),
        "evidence_vnext_readiness": "Readiness",
        "evidence_vnext_totals": "Evidence totals",
        "evidence_vnext_exa_strategy": "Exa strategy",
        "evidence_vnext_next_action": "Next action",
        "evidence_vnext_review_reasons": "Review reasons",
        "evidence_vnext_rejected_reasons": "Rejected reasons",
        "evidence_vnext_open_diagnostic": "Open full diagnostic",
        "entity_resolution": "Entity Resolution",
        "entity_tag": "product and company boundaries",
        "research_pack": "Research Pack",
        "research_pack_tag": "normalized strategic inputs",
        "research_sections": "Sections",
        "surface_map": "Surface Map",
        "surface_map_tag": "owned, product, proof, and external surfaces",
        "product_surfaces": "Product surfaces",
        "source_map": "Source map",
        "competitive_context": "Competitive context",
        "competitive_context_tag": "context only, not audited-brand evidence",
        "parallel_shadow": "Parallel Shadow",
        "parallel_shadow_tag": "external signals for manual review",
        "parallel_shadow_intro": (
            "Parallel is running as an observational provider. This readout summarizes external coverage "
            "candidates for review; it is not used for scoring, TLDR claims, proof points, or recommendations."
        ),
        "parallel_shadow_readout": "External signal readout",
        "parallel_shadow_coverage": "Coverage",
        "parallel_shadow_candidate_count": "External candidates",
        "parallel_shadow_domain_count": "Domains",
        "parallel_shadow_signal_types": "Signal types",
        "parallel_shadow_manual_review": "Manual review candidates",
        "parallel_shadow_missing": "No Parallel shadow data was persisted for this scan.",
        "parallel_shadow_domains": "Domains",
        "parallel_shadow_intents": "Intents",
        "parallel_shadow_results": "Source candidates",
        "tldr_evidence": "TLDR Evidence",
        "tldr_evidence_tag": "what each block used",
        "rejected_gaps": "Rejected / Gaps",
        "rejected_gaps_tag": "bounded interpretation",
        "evidence_gaps": "Evidence gaps",
        "rejected_noise": "Rejected noise",
        "entity_boundary_warnings": "Entity boundary warnings",
        "entity_boundary_warnings_tag": "external evidence quarantined before TLDR input",
        "entity_boundary_rejections": "Quarantined evidence",
        "entity_boundary_open_source": "Open source",
        "no_entity_boundary_warnings": "No entity boundary collisions were persisted for this scan.",
        "methodology_intro": "Method, interpretation rules, and limits behind this scan.",
        "methodology_tag": "methodology details",
        "result_metadata": "Result metadata",
        "result_metadata_tag": "derived compatibility flags",
        "result_version": "Result version",
        "pipeline_version": "Pipeline version",
        "scanner_readiness": "Scanner readiness",
        "generated_with": "Generated with",
        "stale_against_current_pipeline": "Historic against current pipeline",
        "research_pack_metric": "Research Pack",
        "tldr_generation": "TLDR Generation",
        "pipeline": "Pipeline",
        "pipeline_tag": "deterministic steps and LLM step",
        "block_method": "TLDR Block Method",
        "block_method_tag": "what each block is allowed to answer",
        "magenta_signals": "Magenta Circle Signals",
        "magenta_signals_tag": "7 technical inputs",
        "run_limits": "Run Limits",
        "run_limits_tag": "warnings and bounded interpretation",
        "source_basis": "Source basis",
        "validation_notes": "Validation notes",
        "no_validation_notes": "No validation notes were persisted for this scan.",
        "no_limitations": "No explicit limitations were persisted for this scan.",
        "no_clear_signal": "No clear signal detected in the provided sources.",
        "evidence": "Evidence",
    },
    "es": {
        "language": "Idioma",
        "other_lang": "EN",
        "scanner_title": "Brand3 Scanner",
        "scanner_tag": "análisis competitivo y auditoría de 7 capas",
        "manual_summary": "Entrada manual de texto (legacy/debug, no comparable)",
        "manual_label": "Contenido web bruto / copy de landing:",
        "manual_placeholder": "Pega aquí el texto de la homepage...",
        "manual_note": (
            "La entrada manual evita la adquisición de Brand Audit y se marca como evidencia directa legacy. "
            "Úsala solo para debug o revisión ad hoc; los escaneos comparables de producción deben usar URL "
            "o un Brand Audit existente."
        ),
        "from_audit": "desde_brand_audit",
        "from_audit_tag": "reutilizar paquete de evidencia existente",
        "from_audit_intro": (
            "Ruta canónica: generar Magnetism desde un Brand Audit existente. Los escaneos por URL de arriba "
            "crean primero ese mismo tipo de snapshot; esta tabla solo reutiliza uno ya disponible."
        ),
        "use_evidence": "usar evidencia",
        "evidence_vnext_diag": "evidencia vNext",
        "evidence_vnext_json": "JSON crudo",
        "no_audits": "// todavía no hay Brand Audits disponibles — ejecuta una URL arriba o crea un audit normal primero.",
        "recent_scans": "escaneos_recientes",
        "latest_runs": "últimas ejecuciones",
        "view_sheet": "ver ficha",
        "audit_score": "score audit",
        "no_scans": "// todavía no hay escaneos Magnetism — ejecuta el primero arriba.",
        "date": "fecha",
        "brand": "marca",
        "score": "score",
        "coherence": "coherencia",
        "quadrant": "cuadrante de posicionamiento",
        "url": "url",
        "run": "run",
        "result": "resultado",
        "back": "Volver a Brand3 Scanner",
        "home": "Inicio",
        "recent_scans_nav": "Scans recientes",
        "new_scan": "Nuevo scan",
        "sv9_shadow": "SV9 sombra",
        "ranking": "Ranking",
        "tools": "herramientas",
        "scanner_history_intro": "Revisa resultados anteriores y abre su score SV9, evidencia, auditoría y metodología.",
        "base_reading": "Lectura base",
        "research_evidence": "Evidencia de investigación",
        "audit": "Auditoría",
        "audit_tag": "Brand Audit dentro del resultado del scanner",
        "audit_intro": "Lectura ejecutiva de Brand Audit asociada a este resultado del scanner.",
        "audit_unavailable": "Este scan no tiene un snapshot de Brand Audit asociado.",
        "audit_run": "Brand Audit run",
        "executive_summary": "Resumen ejecutivo",
        "primary_risk": "Riesgo principal",
        "primary_opportunity": "Oportunidad principal",
        "internal_audit": "Auditoría interna de score",
        "internal_audit_tag": "proveniencia del score y TLDR v2",
        "audit_status": "Estado de auditoría",
        "score_integrity": "Integridad del score",
        "score_summary": "Resumen de score",
        "computed_score": "Score computado",
        "reviewed_score": "Score revisado",
        "display_score": "Score mostrado",
        "display_score_source": "Fuente del display",
        "display_score_status": "Estado del display",
        "dimension_breakdown": "Desglose por dimensión",
        "confidence_summary": "Resumen de confianza",
        "fallback_flags": "Fallback flags",
        "rules_caps": "Rules / caps",
        "warnings": "Warnings",
        "recommended_action": "Acción recomendada",
        "tldr_v2_internal_summary": "Resumen interno TLDR v2",
        "fingerprint_details": "Detalles del fingerprint",
        "raw_feature_provenance": "Proveniencia cruda de features",
        "reviewed_score_block": "Bloque de score revisado",
        "dimension_audit": "Auditoría por dimensión",
        "findings": "Hallazgos",
        "recommendation": "Recomendación",
        "confidence": "Confianza",
        "legacy_audit": "Fallback de auditoría legacy",
        "evidence_reliability": "Fiabilidad de evidencia",
        "evidence": "Evidencia",
        "evidence_basis": "Base de evidencia",
        "total_evidence": "Evidencia total",
        "overall_status": "Estado general",
        "report_mode": "Modo de informe",
        "dimension_names": {
            "coherencia": "Coherencia",
            "presencia": "Presencia",
            "percepcion": "Percepción",
            "diferenciacion": "Diferenciación",
            "vitalidad": "Vitalidad",
        },
        "methodology_details": "Detalles de metodología",
        "methodology": "Metodología",
        "moodboard": "Moodboard",
        "moodboard_tag": "tablero visual con assets capturados de la marca",
        "moodboard_intro": (
            "Imágenes representativas que la marca publica en sus superficies propias, capturadas durante "
            "este escaneo y organizadas como moodboard junto a la lectura estratégica."
        ),
        "moodboard_hint": "arrastra las imágenes para reorganizar",
        "moodboard_shuffle": "reorganizar",
        "moodboard_empty": (
            "No se capturaron imágenes representativas para este escaneo. El moodboard necesita un run de "
            "Brand Audit con adquisición web persistida."
        ),
        "moodboard_visual_reading": "Lectura visual",
        "moodboard_visual_reading_tag": "bloques estratégicos que enmarcan las imágenes",
        "moodboard_inventory": "Inventario de imágenes",
        "moodboard_inventory_tag": "assets capturados y su rol",
        "moodboard_role": "rol",
        "moodboard_alt": "texto alt",
        "moodboard_roles": {
            "logo": "logo / icono",
            "social_card": "tarjeta social",
            "content": "imagen de página",
        },
        "moodboard_source_note": (
            "Las imágenes se enlazan directamente desde las páginas de la marca tal como se capturaron; un "
            "hueco vacío significa que el asset ya no es accesible."
        ),
        "detail_tag": "9 bloques estratégicos derivados de 7 señales Magenta",
        "no_detected": "(no detectado)",
        "system_reading": "Lectura de sistema TLDR",
        "system_reading_tag": "tensiones y preguntas de validación dentro del TLDR Brand3",
        "client_tldr_v2": "TLDR v2 para cliente",
        "client_tldr_v2_tag": "preview de cliente con score y evidencia",
        "generate_sv9": "Generar SV9",
        "sv9_generation_status": "Generación de SV9",
        "sv9_generation_tag": "materialización del scan sombra",
        "sv9_generation_intro": "Generando el scan sombra V9 desde el snapshot persistido de Brand Audit.",
        "sv9_generation_queued": "esperando para materializar el scan sombra",
        "sv9_generation_ready": "scan sombra listo ...",
        "sv9_generation_ready_link": "→ abrir scan SV9",
        "sv9_generation_back": "← volver al scan",
        "score_reading": "Lectura del score",
        "score_status": "Estado del score",
        "score_note": "Nota del score",
        "evidence_refs": "Referencias de evidencia",
        "tldr_block_names": {
            "core_purpose": "PROPÓSITO CENTRAL",
            "magnetism": "MAGNETISMO",
            "value_proposition": "PROPUESTA DE VALOR",
            "personality": "PERSONALIDAD",
            "brand_idea": "IDEA DE MARCA",
            "attributes": "ATRIBUTOS",
            "values": "VALORES",
            "mission": "MISIÓN",
            "vision": "VISIÓN",
        },
        "credibility_support": "Soporte de credibilidad",
        "strategic_tensions": "Tensiones estratégicas",
        "validation_questions": "Preguntas de validación",
        "diagnosis": "diagnóstico",
        "diagnosis_tag": "limitado por señales observadas y ausentes",
        "limitations": "limitaciones",
        "research_intro": "Grafo de evidencia y Research Pack usados para producir la lectura TLDR Brand3.",
        "research_tag": "evidencia de investigación",
        "evidence_reliability_intro": (
            "Diagnóstico objetivo del Research Pack usado como input del TLDR. Evalúa calidad de evidencia, "
            "no la marca, y no cambia los bloques TLDR."
        ),
        "evidence_reliability_tag": "calidad del input, no de la marca",
        "quality_status": "Estado",
        "quality_score": "Score",
        "quality_gate": "Gate",
        "quality_dimensions": "Dimensiones de calidad",
        "quality_dimensions_tag": "oferta, audiencia, prueba, trazabilidad y ruido",
        "quality_warnings": "Warnings",
        "quality_failures": "Fallos de gate",
        "quality_pack_summary": "Resumen del pack",
        "quality_missing": "No se persistió diagnóstico de calidad del Research Pack para este escaneo.",
        "no_quality_warnings": "No se persistieron warnings.",
        "no_quality_failures": "No hay fallos de gate.",
        "pack_source": "Fuente del pack",
        "tldr_mode": "Modo TLDR",
        "evidence_vnext_contract": "Contrato de evidencia vNext",
        "evidence_vnext_contract_tag": "readiness de promoción e higiene de fuentes",
        "evidence_vnext_contract_intro": (
            "Resumen operativo del gate de evidencia vNext para el Brand Audit asociado. Muestra qué puede "
            "alimentar el Research Pack y qué quedó en revisión o ruido."
        ),
        "evidence_vnext_readiness": "Readiness",
        "evidence_vnext_totals": "Totales de evidencia",
        "evidence_vnext_exa_strategy": "Estrategia Exa",
        "evidence_vnext_next_action": "Siguiente acción",
        "evidence_vnext_review_reasons": "Razones de revisión",
        "evidence_vnext_rejected_reasons": "Razones de rechazo",
        "evidence_vnext_open_diagnostic": "Abrir diagnóstico completo",
        "entity_resolution": "Resolución de entidad",
        "entity_tag": "límites entre producto y compañía",
        "research_pack": "Research Pack",
        "research_pack_tag": "inputs estratégicos normalizados",
        "research_sections": "Secciones",
        "surface_map": "Mapa de superficies",
        "surface_map_tag": "superficies owned, producto, prueba y externas",
        "product_surfaces": "Superficies de producto",
        "source_map": "Mapa de fuentes",
        "competitive_context": "Contexto competitivo",
        "competitive_context_tag": "solo contexto, no evidencia de la marca auditada",
        "parallel_shadow": "Parallel Shadow",
        "parallel_shadow_tag": "señales externas para revisión manual",
        "parallel_shadow_intro": (
            "Parallel está corriendo como proveedor observacional. Esta lectura resume candidatos de "
            "cobertura externa para revisión; no se usa en scoring, claims TLDR, proof points ni recomendaciones."
        ),
        "parallel_shadow_readout": "Lectura de señales externas",
        "parallel_shadow_coverage": "Cobertura",
        "parallel_shadow_candidate_count": "Candidatos externos",
        "parallel_shadow_domain_count": "Dominios",
        "parallel_shadow_signal_types": "Tipos de señal",
        "parallel_shadow_manual_review": "Candidatos a revisión manual",
        "parallel_shadow_missing": "No se persistió data shadow de Parallel para este escaneo.",
        "parallel_shadow_domains": "Dominios",
        "parallel_shadow_intents": "Intents",
        "parallel_shadow_results": "Fuentes candidatas",
        "tldr_evidence": "Evidencia TLDR",
        "tldr_evidence_tag": "qué usó cada bloque",
        "rejected_gaps": "Rechazado / Gaps",
        "rejected_gaps_tag": "interpretación acotada",
        "evidence_gaps": "Gaps de evidencia",
        "rejected_noise": "Ruido rechazado",
        "entity_boundary_warnings": "Warnings de límite de entidad",
        "entity_boundary_warnings_tag": "evidencia externa en cuarentena antes del TLDR",
        "entity_boundary_rejections": "Evidencia cuarentenada",
        "entity_boundary_open_source": "Abrir fuente",
        "no_entity_boundary_warnings": "No se persistieron colisiones de límite de entidad para este escaneo.",
        "methodology_intro": "Método, reglas de interpretación y límites detrás de este escaneo.",
        "methodology_tag": "detalles de metodología",
        "result_metadata": "Metadata del resultado",
        "result_metadata_tag": "flags derivados de compatibilidad",
        "result_version": "Versión del resultado",
        "pipeline_version": "Versión del pipeline",
        "scanner_readiness": "Readiness del scanner",
        "generated_with": "Generado con",
        "stale_against_current_pipeline": "Histórico frente al pipeline actual",
        "research_pack_metric": "Research Pack",
        "tldr_generation": "Generación TLDR",
        "pipeline": "Pipeline",
        "pipeline_tag": "pasos deterministas y paso LLM",
        "block_method": "Método de bloques TLDR",
        "block_method_tag": "qué puede responder cada bloque",
        "magenta_signals": "Señales Magenta Circle",
        "magenta_signals_tag": "7 inputs técnicos",
        "run_limits": "Límites de ejecución",
        "run_limits_tag": "warnings e interpretación acotada",
        "source_basis": "Base de fuentes",
        "validation_notes": "Notas de validación",
        "no_validation_notes": "No se persistieron notas de validación para este escaneo.",
        "no_limitations": "No se persistieron limitaciones explícitas para este escaneo.",
        "no_clear_signal": "No se detectó una señal clara en las fuentes proporcionadas.",
        "evidence": "Evidencia",
    },
}
