"""End-to-end finalization implementation for Brand3 analysis runs."""

from __future__ import annotations

from src.services.run_result_assembly import build_run_result
from src.services.run_finalization_persistence import persist_finalization_artifacts


def finalize_run(
    *,
    service,
    store,
    run_id: int | None,
    brand_name: str,
    url: str,
    web_data,
    content_web,
    exa_data,
    content_source: str,
    data_quality: str,
    partial_dimensions,
    social_data,
    use_llm: bool,
    use_social: bool,
    use_competitors: bool,
    skip_visual_analysis: bool,
    llm,
    llm_provider,
    llm_skipped_reason,
    calibration_profile: str,
    niche_classification: dict,
    research_pack_for_feature_prompts,
    entity_discovery: dict,
    discovery_search_plan: dict,
    discovery_evidence_preview: dict,
    discovery_enrichment_payload: dict,
    discovery_payload: dict,
    discovery_trust_basis: dict,
    discovery_calibration_hint: dict,
    discovery_calibration_decision: dict,
    entity_research_packet: dict,
    acquisition_provenance: dict,
    acquisition_steps: dict,
    raw_input_cache: dict,
    screenshot_capture: dict | None,
    base_data_sources: dict,
    social_limitation: str | None,
    context_data,
    features_by_dim: dict,
    brand_score,
    summary: str,
    progress_cb=None,
    cancel_check=None,
) -> dict:
    result, run_audit_context, _, _ = build_run_result(
        service=service,
        store=store,
        run_id=run_id,
        web_data=web_data,
        content_web=content_web,
        exa_data=exa_data,
        content_source=content_source,
        data_quality=data_quality,
        partial_dimensions=partial_dimensions,
        social_data=social_data,
        use_llm=use_llm,
        use_social=use_social,
        use_competitors=use_competitors,
        skip_visual_analysis=skip_visual_analysis,
        llm=llm,
        llm_provider=llm_provider,
        llm_skipped_reason=llm_skipped_reason,
        calibration_profile=calibration_profile,
        niche_classification=niche_classification,
        research_pack_for_feature_prompts=research_pack_for_feature_prompts,
        entity_discovery=entity_discovery,
        discovery_search_plan=discovery_search_plan,
        discovery_evidence_preview=discovery_evidence_preview,
        discovery_enrichment_payload=discovery_enrichment_payload,
        discovery_payload=discovery_payload,
        discovery_trust_basis=discovery_trust_basis,
        discovery_calibration_hint=discovery_calibration_hint,
        discovery_calibration_decision=discovery_calibration_decision,
        entity_research_packet=entity_research_packet,
        acquisition_provenance=acquisition_provenance,
        acquisition_steps=acquisition_steps,
        raw_input_cache=raw_input_cache,
        screenshot_capture=screenshot_capture,
        base_data_sources=base_data_sources,
        social_limitation=social_limitation,
        context_data=context_data,
        features_by_dim=features_by_dim,
        brand_score=brand_score,
        summary=summary,
    )
    persist_finalization_artifacts(
        service=service,
        store=store,
        run_id=run_id,
        result=result,
        social_data=social_data,
        use_llm=use_llm,
        llm=llm,
        summary=summary,
        brand_score=brand_score,
        run_audit_context=run_audit_context,
    )
    return result
