"""Fixture records and manifest for the phase zero catalog."""

from __future__ import annotations

from src.visual_signature.phase_zero.catalog_registries import OBSERVATION_REGISTRY, SCORING_REGISTRY, STATE_REGISTRY, TRANSITION_REGISTRY, UNCERTAINTY_POLICY
from src.visual_signature.phase_zero.catalog_support import now_timestamp as _now, uncertainty_profile as _uncertainty_profile
from src.visual_signature.phase_zero.models import (
    DATASET_ELIGIBILITY_SCHEMA_VERSION,
    MUTATION_AUDIT_SCHEMA_VERSION,
    OBSERVATION_RECORD_SCHEMA_VERSION,
    PHASE_ZERO_TAXONOMY_VERSION,
    REASONING_TRACE_SCHEMA_VERSION,
    REVIEW_RECORD_SCHEMA_VERSION,
    STATE_RECORD_SCHEMA_VERSION,
    TRANSITION_RECORD_SCHEMA_VERSION,
    UNCERTAINTY_PROFILE_SCHEMA_VERSION,
)


UNCERTAINTY_PROFILE = _uncertainty_profile(0.78, reasons=["mixed_affordance_signals"], known_unknowns=["overlay may affect CTA visibility"], reviewer_required=True)

REASONING_TRACE = {
    "schema_version": REASONING_TRACE_SCHEMA_VERSION,
    "taxonomy_version": PHASE_ZERO_TAXONOMY_VERSION,
    "record_type": "reasoning_trace",
    "trace_id": "trace_phase_zero_example",
    "created_at": _now(),
    "summary": "The viewport is readable but partially obstructed, so human review is required.",
    "statements": [
        {"statement": "A cookie modal covers the lower portion of the viewport.", "confidence": 0.92, "evidence_refs": ["raw_screenshot_path"], "warnings": []},
        {"statement": "The primary CTA is visible but its clarity is reduced by the overlay.", "confidence": 0.78, "evidence_refs": ["raw_screenshot_path", "dom_snapshot_ref"], "warnings": []},
    ],
    "unsupported_inference_warnings": [],
    "review_required": True,
    "lineage_refs": ["capture:phase-zero-example"],
}

OBSERVATION_RECORD = {
    "schema_version": OBSERVATION_RECORD_SCHEMA_VERSION,
    "taxonomy_version": PHASE_ZERO_TAXONOMY_VERSION,
    "record_type": "perceptual_observation",
    "record_id": "obs_phase_zero_example",
    "created_at": _now(),
    "capture_id": "cap_phase_zero_example",
    "brand_name": "Example Brand",
    "website_url": "https://example.com",
    "perception_layer": "functional",
    "observation_key": "cta_clarity",
    "observation_value": "low",
    "confidence": 0.78,
    "uncertainty": UNCERTAINTY_PROFILE,
    "evidence_refs": ["raw_screenshot_path", "dom_snapshot_ref"],
    "reasoning_trace": REASONING_TRACE,
    "lineage_refs": ["capture:phase-zero-example"],
}

STATE_RECORD = {
    "schema_version": STATE_RECORD_SCHEMA_VERSION,
    "taxonomy_version": PHASE_ZERO_TAXONOMY_VERSION,
    "record_type": "perceptual_state",
    "record_id": "state_phase_zero_example",
    "created_at": _now(),
    "capture_id": "cap_phase_zero_example",
    "brand_name": "Example Brand",
    "website_url": "https://example.com",
    "perceptual_state": "REVIEW_REQUIRED_STATE",
    "confidence": 0.91,
    "uncertainty": _uncertainty_profile(0.91, reasons=["insufficient_viewport"], known_unknowns=["overlay may hide below-the-fold intent"], reviewer_required=True),
    "transitions": [
        {"schema_version": TRANSITION_RECORD_SCHEMA_VERSION, "taxonomy_version": PHASE_ZERO_TAXONOMY_VERSION, "record_type": "transition_record", "transition_id": "transition_phase_zero_example", "created_at": _now(), "capture_id": "cap_phase_zero_example", "from_state": "RAW_STATE", "to_state": "OBSTRUCTED_STATE", "reason": "viewport_obstruction_detected", "confidence": 0.93, "evidence_refs": ["raw_screenshot_path"], "lineage_refs": ["capture:phase-zero-example"], "mutation_ref": None, "notes": ["cookie modal visible"]},
    ],
    "reasoning_trace": REASONING_TRACE,
    "lineage_refs": ["capture:phase-zero-example"],
}

TRANSITION_RECORD = {
    "schema_version": TRANSITION_RECORD_SCHEMA_VERSION,
    "taxonomy_version": PHASE_ZERO_TAXONOMY_VERSION,
    "record_type": "transition_record",
    "transition_id": "transition_phase_zero_example",
    "created_at": _now(),
    "capture_id": "cap_phase_zero_example",
    "from_state": "RAW_STATE",
    "to_state": "OBSTRUCTED_STATE",
    "reason": "viewport_obstruction_detected",
    "confidence": 0.93,
    "evidence_refs": ["raw_screenshot_path"],
    "lineage_refs": ["capture:phase-zero-example"],
    "mutation_ref": None,
    "notes": ["cookie modal visible"],
}

MUTATION_AUDIT = {
    "schema_version": MUTATION_AUDIT_SCHEMA_VERSION,
    "taxonomy_version": PHASE_ZERO_TAXONOMY_VERSION,
    "record_type": "mutation_audit",
    "mutation_id": "mutation_phase_zero_example",
    "created_at": _now(),
    "capture_id": "cap_phase_zero_example",
    "brand_name": "Example Brand",
    "website_url": "https://example.com",
    "mutation_type": "cookie_banner_dismissal",
    "before_state": "ELIGIBLE_FOR_SAFE_INTERVENTION",
    "after_state": "REVIEW_REQUIRED_STATE",
    "attempted": True,
    "successful": False,
    "reversible": True,
    "risk_level": "low",
    "trigger": "close",
    "evidence_preserved": True,
    "before_artifact_ref": "examples/visual_signature/phase_zero/fixtures/raw.example.png",
    "after_artifact_ref": "examples/visual_signature/phase_zero/fixtures/clean_attempt.example.png",
    "lineage_refs": ["capture:phase-zero-example", "transition:transition_phase_zero_example"],
    "integrity_notes": ["raw_viewport_preserved_as_primary_evidence", "clean_attempt_is_supplemental_only", "safe_mutation_failed_without_overwriting_raw_state"],
}

DATASET_ELIGIBILITY_RECORD = {
    "schema_version": DATASET_ELIGIBILITY_SCHEMA_VERSION,
    "taxonomy_version": PHASE_ZERO_TAXONOMY_VERSION,
    "record_type": "dataset_eligibility",
    "record_id": "elig_phase_zero_example",
    "created_at": _now(),
    "capture_id": "cap_phase_zero_example",
    "brand_name": "Example Brand",
    "website_url": "https://example.com",
    "eligible": True,
    "reasons": ["raw evidence preserved", "schema valid", "mutation lineage preserved", "no unsupported inference", "review completed"],
    "blocked_reasons": [],
    "raw_evidence_preserved": True,
    "mutation_lineage_preserved": True,
    "schema_valid": True,
    "review_required": True,
    "review_completed": True,
    "uncertainty_below_threshold": False,
    "confidence_threshold": 0.8,
    "observed_confidence": 0.91,
    "unsupported_inference_found": False,
    "evidence_refs": ["raw_screenshot_path", "dom_snapshot_ref"],
    "lineage_refs": ["capture:phase-zero-example", "mutation:mutation_phase_zero_example"],
}

REVIEW_RECORD = {
    "schema_version": REVIEW_RECORD_SCHEMA_VERSION,
    "taxonomy_version": PHASE_ZERO_TAXONOMY_VERSION,
    "record_type": "review_record",
    "review_id": "review_phase_zero_example",
    "capture_id": "cap_phase_zero_example",
    "reviewer_id": "reviewer_alpha",
    "reviewed_at": _now(),
    "review_status": "approved",
    "visually_supported": "partial",
    "unsupported_inference_present": False,
    "uncertainty_accepted": True,
    "notes": ["Viewport obstruction is supported by evidence.", "Uncertainty is explicitly acknowledged and accepted."],
}

PHASE_ZERO_MANIFEST = {
    "schema_version": "phase-zero-manifest-1",
    "phase": "phase_zero",
    "taxonomy_version": PHASE_ZERO_TAXONOMY_VERSION,
    "schema_versions": {
        "observation_registry": OBSERVATION_REGISTRY["schema_version"],
        "state_registry": STATE_REGISTRY["schema_version"],
        "transition_registry": TRANSITION_REGISTRY["schema_version"],
        "scoring_registry": SCORING_REGISTRY["schema_version"],
        "uncertainty_policy": UNCERTAINTY_POLICY["schema_version"],
        "uncertainty_profile": UNCERTAINTY_PROFILE_SCHEMA_VERSION,
        "reasoning_trace": REASONING_TRACE_SCHEMA_VERSION,
        "review_record": REVIEW_RECORD_SCHEMA_VERSION,
        "perceptual_observation": OBSERVATION_RECORD_SCHEMA_VERSION,
        "perceptual_state": STATE_RECORD_SCHEMA_VERSION,
        "transition_record": TRANSITION_RECORD_SCHEMA_VERSION,
        "mutation_audit": MUTATION_AUDIT_SCHEMA_VERSION,
        "dataset_eligibility": DATASET_ELIGIBILITY_SCHEMA_VERSION,
    },
    "directories": ["taxonomy", "schemas", "fixtures"],
    "files": [
        "taxonomy/observation_registry.json",
        "taxonomy/state_registry.json",
        "taxonomy/transition_registry.json",
        "taxonomy/scoring_registry.json",
        "taxonomy/uncertainty_policy.json",
        "schemas/observation_registry.schema.json",
        "schemas/state_registry.schema.json",
        "schemas/transition_registry.schema.json",
        "schemas/scoring_registry.schema.json",
        "schemas/uncertainty_policy.schema.json",
        "schemas/uncertainty_profile.schema.json",
        "schemas/reasoning_trace.schema.json",
        "schemas/perceptual_observation.schema.json",
        "schemas/perceptual_state.schema.json",
        "schemas/transition_record.schema.json",
        "schemas/mutation_audit.schema.json",
        "schemas/dataset_eligibility.schema.json",
        "fixtures/observation_record.example.json",
        "fixtures/state_record.example.json",
        "fixtures/transition_record.example.json",
        "fixtures/mutation_audit.example.json",
        "fixtures/reasoning_trace.example.json",
        "fixtures/uncertainty_profile.example.json",
        "fixtures/dataset_eligibility.example.json",
        "fixtures/review_record.example.json",
        "manifests/phase_zero_manifest.json",
    ],
}
