"""Keyword groups and source type constants for strategic evidence packets."""

from __future__ import annotations

from src.reports.vertical_signals import vertical_group_keywords

GROUP_KEYWORDS: dict[str, tuple[str, ...]] = {
    "hero_claims": (
        "introducing",
        "meet ",
        "built for",
        "designed for",
        "purpose-built",
        "just do it",
        "earn every",
        "system for",
        "platform for",
    ),
    "product_offer": (
        "platform",
        "plataforma",
        "infrastructure",
        "infraestructura",
        "api",
        "payments",
        "pagos",
        "billing",
        "facturacion",
        "facturación",
        "services",
        "servicios",
        "products",
        "productos",
        "software",
        "model",
        "ai assistant",
        "chatbot",
        "banking",
        "wealth management",
        "private banking",
        "business analyst",
        "human intelligence",
        "research people",
        "research people and companies",
        "brand identities",
        "ai-powered search",
        "product discovery",
        "merchandising",
        "conversions",
        "shopper intent",
        "ecommerce",
        "e-commerce",
        "branding solution",
        "brand execution",
        "brand and website",
        "deliverables",
        "calendar app",
        "productivity tools",
        "extendable launcher",
        "application launcher",
        "observability service",
        "monitoring",
        "portfolio platform",
        "jobs and recruiting site",
    )
    + vertical_group_keywords("product_offer"),
    "audience": (
        "teams",
        "agents",
        "developers",
        "businesses",
        "founders",
        "startups",
        "finance teams",
        "sales teams",
        "wealth managers",
        "creators",
        "customers",
        "clients",
        "shopper",
        "shoppers",
        "manufacturer",
        "manufacturers",
        "people and companies",
        "enterprise",
        "fortune 100",
        "asesores",
        "empresas",
        "clientes",
        "fabricante",
        "fabricantes",
        "distribuidor",
        "distribuidores",
        "atletas",
        "athletes",
    ),
    "outcome": (
        "helps",
        "help ",
        "eliminate risks",
        "secure your competitive advantage",
        "grow",
        "increase",
        "reduce",
        "automate",
        "productive",
        "productivity",
        "efficient",
        "efficiency",
        "drive success",
        "build relationships",
        "get things done",
        "make people talk",
        "solve problems",
        "learn faster",
        "faster",
        "deploy instantly",
        "build and ship",
        "develop and ship",
        "ship digital products",
        "scale",
        "improve product discovery",
        "increasing conversions",
        "boosts conversions",
        "reduce no-result searches",
        "streamline",
        "centralise",
        "centralize",
        "gestionar",
        "hacer crecer",
        "automatizar",
        "reducir costes",
        "reduce costes",
        "facilitar",
        "optimiza",
        "asegura",
        "empowering",
        "impulsando",
    )
    + vertical_group_keywords("outcome"),
    "mission_language": (
        "we build",
        "we create",
        "we provide",
        "we help",
        "we make",
        "we enable",
        "we develop",
        "we empower",
        "our mission",
        "on a mission to",
        "make developers",
        "make teams",
        "help companies",
        "ayuda a",
        "ofrece",
        "creamos",
        "proporcionamos",
    ),
    "vision_language": (
        "future of",
        "built for the future",
        "new model",
        "new paradigm",
        "transform the future",
        "transforming the future",
        "shape the future",
        "creative entity",
        "creative work",
        "wield power",
        "world stage",
        "futuro de",
        "nuevo modelo",
        "nueva generación",
        "transformar la categoría",
        "transformar el futuro",
    ),
    "values_language": (
        "trusted",
        "trust",
        "secure",
        "security",
        "privacy",
        "transparent",
        "sustainable",
        "regenerative",
        "confianza",
        "seguro",
        "seguridad",
        "sostenible",
    )
    + vertical_group_keywords("values_language"),
    "personality_tone": (
        "bold",
        "fast",
        "simple",
        "powerful",
        "precise",
        "creative",
        "ambition",
        "culture",
        "inspire",
        "inspirar",
        "innovative",
        "innovadores",
    ),
    "proof_points": (
        "customers",
        "customer",
        "clients",
        "client",
        "clientes",
        "cliente",
        "trusted by",
        "con la confianza",
        "case study",
        "case studies",
        "customer story",
        "success story",
        "caso de éxito",
        "casos de éxito",
        "testimonial",
        "testimonials",
        "testimonio",
        "testimonios",
        "reviews",
        "review",
        "reseñas",
        "resenas",
        "opiniones",
        "millions",
        "global",
        "leader",
        "used by",
        "raises",
        "funding",
    ),
    "third_party_context": (
        "raises",
        "funding",
        "report",
        "market",
        "competitor",
        "news",
    ),
}

OWNED_SOURCE_TYPES = {"owned", "social", "owned_raw"}
CONTEXT_SOURCE_TYPES = {"encyclopedic", "news", "review", "other", "changelog"}

NOISE_MARKERS = (
    "; evidence=",
    "source_type=",
    "dimension=",
    "feature=",
    "__next_data__",
    "graphql api",
    "product roadmap",
    "rg --files",
    "/bin/bash",
)
