"""Facade implementation for TLDR block interpreter helpers."""

from __future__ import annotations

from src.features.magnetism import block_interpreters_helpers_signals_impl as _signals
from src.features.magnetism import block_interpreters_helpers_text_impl as _text

_clean_candidate_text = _text._clean_candidate_text
_clean_layer_candidate_text = _text._clean_layer_candidate_text
_contains_keyword = _signals._contains_keyword
_has_operating_activity_signal = _signals._has_operating_activity_signal
_has_formal_mission_signal = _signals._has_formal_mission_signal
_has_future_signal = _signals._has_future_signal
_has_offer_signal = _signals._has_offer_signal
_has_audience_signal = _signals._has_audience_signal
_has_outcome_signal = _signals._has_outcome_signal
_is_vague_mission_slogan = _signals._is_vague_mission_slogan
_is_values_statement_as_mission = _signals._is_values_statement_as_mission
_is_feed_or_article_noise = _signals._is_feed_or_article_noise
_is_rhetorical_future_question_noise = _signals._is_rhetorical_future_question_noise
_is_market_prediction_noise = _signals._is_market_prediction_noise
_is_testimonial_evidence = _signals._is_testimonial_evidence
_is_truncated_evidence = _signals._is_truncated_evidence
_is_bad_value_prop_candidate = _text._is_bad_value_prop_candidate
_is_weak_value_prop_addition = _text._is_weak_value_prop_addition
_looks_like_web_chrome_or_navigation_blob = _signals._looks_like_web_chrome_or_navigation_blob
_looks_like_portfolio_case_card = _signals._looks_like_portfolio_case_card
_looks_like_concatenated_copy = _signals._looks_like_concatenated_copy
_is_developer_cloud_positioning = _text._is_developer_cloud_positioning
_clean_value_prop_answer_text = _text._clean_value_prop_answer_text
_value_proposition_answer = _text._value_proposition_answer
_mission_answer = _text._mission_answer
_sentence_like_evidence_segments = _text._sentence_like_evidence_segments
_representative_evidence_score = _text._representative_evidence_score
_representative_evidence_phrase = _text._representative_evidence_phrase
_evidence_list = _text._evidence_list
_sentences = _text._sentences
_is_navigation_noise = _signals._is_navigation_noise
