"""Facade for tail-text support helpers."""

from __future__ import annotations

from .extractor_tail_text_support_blocks import (
    apply_block_specific_content_rules,
    compose_personality_content,
    default_tldr_mode,
    default_tldr_rationale,
    derive_brand_idea_block,
    derive_mission_block,
    derive_personality_block,
    derive_vision_block,
    enrich_layers_from_legacy_text,
    first_layer_evidences,
    joined_layer_evidence,
)
from .extractor_tail_text_support_summary import (
    add_legacy_fields,
    brand_audit_evidence_packet_summary,
    brand_audit_evidence_text,
    derive_evidence_packet_summary,
    derive_system_reading,
    is_unusable_audit_quote,
    legacy_value,
    snapshot_limitations,
    visual_semantics_from_snapshot,
)
from .extractor_tail_text_support_utils import (
    clean_evidence_phrase,
    clean_optional_string,
    contains_keyword,
    evidence_list,
    extract_three_terms,
    first_matching_sentence,
    heuristic_finding,
    infer_brand_name,
    is_navigation_noise,
    normalize_evidence,
    sentences_from_text,
    tldr_content_from_layer,
    trim_evidence,
)

__all__ = [
    "apply_block_specific_content_rules",
    "clean_evidence_phrase",
    "clean_optional_string",
    "contains_keyword",
    "compose_personality_content",
    "default_tldr_mode",
    "default_tldr_rationale",
    "derive_brand_idea_block",
    "derive_evidence_packet_summary",
    "derive_mission_block",
    "derive_personality_block",
    "derive_system_reading",
    "derive_vision_block",
    "enrich_layers_from_legacy_text",
    "extract_three_terms",
    "evidence_list",
    "first_layer_evidences",
    "first_matching_sentence",
    "heuristic_finding",
    "infer_brand_name",
    "is_navigation_noise",
    "is_unusable_audit_quote",
    "joined_layer_evidence",
    "normalize_evidence",
    "sentences_from_text",
    "add_legacy_fields",
    "brand_audit_evidence_packet_summary",
    "brand_audit_evidence_text",
    "legacy_value",
    "snapshot_limitations",
    "tldr_content_from_layer",
    "trim_evidence",
    "visual_semantics_from_snapshot",
]
