"""Evidence-only corpus expansion scaffold for Visual Signature."""

from src.visual_signature._internal.lazy import make_lazy_dir, make_lazy_getattr

__all__ = [
    "CORPUS_EXPANSION_MANIFEST_SCHEMA_VERSION",
    "CORPUS_EXPANSION_METRICS_SCHEMA_VERSION",
    "CORPUS_EXPANSION_QUEUE_ITEM_SCHEMA_VERSION",
    "CORPUS_EXPANSION_READINESS_SCHEMA_VERSION",
    "CORPUS_EXPANSION_REVIEW_QUEUE_SCHEMA_VERSION",
    "CorpusExpansionManifest",
    "CorpusExpansionMetrics",
    "CorpusExpansionQueueItem",
    "CorpusExpansionQueueState",
    "CorpusExpansionReadinessAssessment",
    "CorpusExpansionReadinessStatus",
    "CorpusExpansionReviewOutcome",
    "CorpusExpansionReviewQueue",
    "ConfidenceBucket",
    "ValidationResult",
    "READINESS_MAX_CONTRADICTION_RATE",
    "READINESS_MAX_UNRESOLVED_RATE",
    "READINESS_MIN_CATEGORY_DEPTH",
    "READINESS_MIN_CONFIDENCE_BUCKETS",
    "READINESS_MIN_REVIEWED_CAPTURES",
    "READINESS_MIN_REVIEWER_COVERAGE",
    "READINESS_MIN_TOTAL_CAPTURES",
    "REVIEWER_WORKFLOW_PILOT_RECORD_TYPE",
    "REVIEWER_WORKFLOW_PILOT_SCHEMA_VERSION",
    "REVIEWER_VIEWER_RECORD_TYPE",
    "REVIEWER_VIEWER_SCHEMA_VERSION",
    "assess_corpus_expansion_bundle",
    "assess_corpus_expansion_readiness",
    "build_corpus_expansion_manifest",
    "build_corpus_expansion_manifest_markdown",
    "build_corpus_expansion_metrics",
    "build_corpus_expansion_review_queue",
    "build_corpus_expansion_seed",
    "build_default_corpus_expansion_seed",
    "build_reviewer_packets",
    "build_reviewer_workflow_pilot",
    "build_reviewer_viewer_bundle",
    "corpus_expansion_metrics_markdown",
    "normalize_queue_items",
    "reviewer_workflow_pilot_markdown",
    "review_queue_items_to_dicts",
    "sample_review_queue_items",
    "validate_corpus_expansion_bundle",
    "validate_corpus_expansion_manifest",
    "validate_corpus_expansion_manifest_payload",
    "validate_corpus_expansion_metrics",
    "validate_corpus_expansion_metrics_payload",
    "validate_corpus_expansion_queue_item",
    "validate_corpus_expansion_readiness_payload",
    "validate_corpus_expansion_review_queue",
    "validate_corpus_expansion_review_queue_payload",
    "validate_reviewer_packets",
    "validate_reviewer_workflow_pilot_payload",
    "validate_reviewer_viewer_bundle",
    "write_corpus_expansion_bundle",
    "write_reviewer_packets",
    "write_reviewer_workflow_pilot",
    "write_reviewer_viewer_bundle",
    "write_review_queue",
]

_EXPORTS = {
    "CORPUS_EXPANSION_MANIFEST_SCHEMA_VERSION": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "CORPUS_EXPANSION_MANIFEST_SCHEMA_VERSION",
    ),
    "CORPUS_EXPANSION_METRICS_SCHEMA_VERSION": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "CORPUS_EXPANSION_METRICS_SCHEMA_VERSION",
    ),
    "CORPUS_EXPANSION_QUEUE_ITEM_SCHEMA_VERSION": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "CORPUS_EXPANSION_QUEUE_ITEM_SCHEMA_VERSION",
    ),
    "CORPUS_EXPANSION_READINESS_SCHEMA_VERSION": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "CORPUS_EXPANSION_READINESS_SCHEMA_VERSION",
    ),
    "CORPUS_EXPANSION_REVIEW_QUEUE_SCHEMA_VERSION": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "CORPUS_EXPANSION_REVIEW_QUEUE_SCHEMA_VERSION",
    ),
    "CorpusExpansionManifest": ("src.visual_signature.corpus_expansion.corpus_expansion_models", "CorpusExpansionManifest"),
    "CorpusExpansionMetrics": ("src.visual_signature.corpus_expansion.corpus_expansion_models", "CorpusExpansionMetrics"),
    "CorpusExpansionQueueItem": ("src.visual_signature.corpus_expansion.corpus_expansion_models", "CorpusExpansionQueueItem"),
    "CorpusExpansionQueueState": ("src.visual_signature.corpus_expansion.corpus_expansion_models", "CorpusExpansionQueueState"),
    "CorpusExpansionReadinessAssessment": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "CorpusExpansionReadinessAssessment",
    ),
    "CorpusExpansionReadinessStatus": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "CorpusExpansionReadinessStatus",
    ),
    "CorpusExpansionReviewOutcome": ("src.visual_signature.corpus_expansion.corpus_expansion_models", "CorpusExpansionReviewOutcome"),
    "CorpusExpansionReviewQueue": ("src.visual_signature.corpus_expansion.corpus_expansion_models", "CorpusExpansionReviewQueue"),
    "ConfidenceBucket": ("src.visual_signature.corpus_expansion.corpus_expansion_models", "ConfidenceBucket"),
    "ValidationResult": ("src.visual_signature.corpus_expansion.corpus_expansion_models", "ValidationResult"),
    "READINESS_MAX_CONTRADICTION_RATE": ("src.visual_signature.corpus_expansion.corpus_metrics", "READINESS_MAX_CONTRADICTION_RATE"),
    "READINESS_MAX_UNRESOLVED_RATE": ("src.visual_signature.corpus_expansion.corpus_metrics", "READINESS_MAX_UNRESOLVED_RATE"),
    "READINESS_MIN_CATEGORY_DEPTH": ("src.visual_signature.corpus_expansion.corpus_metrics", "READINESS_MIN_CATEGORY_DEPTH"),
    "READINESS_MIN_CONFIDENCE_BUCKETS": ("src.visual_signature.corpus_expansion.corpus_metrics", "READINESS_MIN_CONFIDENCE_BUCKETS"),
    "READINESS_MIN_REVIEWED_CAPTURES": ("src.visual_signature.corpus_expansion.corpus_metrics", "READINESS_MIN_REVIEWED_CAPTURES"),
    "READINESS_MIN_REVIEWER_COVERAGE": ("src.visual_signature.corpus_expansion.corpus_metrics", "READINESS_MIN_REVIEWER_COVERAGE"),
    "READINESS_MIN_TOTAL_CAPTURES": ("src.visual_signature.corpus_expansion.corpus_metrics", "READINESS_MIN_TOTAL_CAPTURES"),
    "REVIEWER_WORKFLOW_PILOT_RECORD_TYPE": (
        "src.visual_signature.corpus_expansion.reviewer_workflow_pilot",
        "REVIEWER_WORKFLOW_PILOT_RECORD_TYPE",
    ),
    "REVIEWER_WORKFLOW_PILOT_SCHEMA_VERSION": (
        "src.visual_signature.corpus_expansion.reviewer_workflow_pilot",
        "REVIEWER_WORKFLOW_PILOT_SCHEMA_VERSION",
    ),
    "REVIEWER_VIEWER_RECORD_TYPE": ("src.visual_signature.corpus_expansion.reviewer_viewer", "REVIEWER_VIEWER_RECORD_TYPE"),
    "REVIEWER_VIEWER_SCHEMA_VERSION": ("src.visual_signature.corpus_expansion.reviewer_viewer", "REVIEWER_VIEWER_SCHEMA_VERSION"),
    "assess_corpus_expansion_bundle": ("src.visual_signature.corpus_expansion.corpus_expansion_manifest", "assess_corpus_expansion_bundle"),
    "assess_corpus_expansion_readiness": ("src.visual_signature.corpus_expansion.corpus_metrics", "assess_corpus_expansion_readiness"),
    "build_corpus_expansion_manifest": ("src.visual_signature.corpus_expansion.corpus_expansion_manifest", "build_corpus_expansion_manifest"),
    "build_corpus_expansion_manifest_markdown": (
        "src.visual_signature.corpus_expansion.corpus_expansion_manifest",
        "build_corpus_expansion_manifest_markdown",
    ),
    "build_corpus_expansion_metrics": ("src.visual_signature.corpus_expansion.corpus_metrics", "build_corpus_expansion_metrics"),
    "build_corpus_expansion_review_queue": ("src.visual_signature.corpus_expansion.corpus_review_queue", "build_corpus_expansion_review_queue"),
    "build_corpus_expansion_seed": ("src.visual_signature.corpus_expansion.corpus_sampling", "build_default_corpus_expansion_seed"),
    "build_default_corpus_expansion_seed": ("src.visual_signature.corpus_expansion.corpus_sampling", "build_default_corpus_expansion_seed"),
    "build_reviewer_packets": ("src.visual_signature.corpus_expansion.reviewer_packets", "build_reviewer_packets"),
    "build_reviewer_workflow_pilot": ("src.visual_signature.corpus_expansion.reviewer_workflow_pilot", "build_reviewer_workflow_pilot"),
    "build_reviewer_viewer_bundle": ("src.visual_signature.corpus_expansion.reviewer_viewer", "build_reviewer_viewer_bundle"),
    "corpus_expansion_metrics_markdown": ("src.visual_signature.corpus_expansion.corpus_metrics", "corpus_expansion_metrics_markdown"),
    "normalize_queue_items": ("src.visual_signature.corpus_expansion.corpus_sampling", "normalize_queue_items"),
    "reviewer_workflow_pilot_markdown": (
        "src.visual_signature.corpus_expansion.reviewer_workflow_pilot",
        "reviewer_workflow_pilot_markdown",
    ),
    "review_queue_items_to_dicts": ("src.visual_signature.corpus_expansion.corpus_review_queue", "review_queue_items_to_dicts"),
    "sample_review_queue_items": ("src.visual_signature.corpus_expansion.corpus_sampling", "sample_review_queue_items"),
    "validate_corpus_expansion_bundle": ("src.visual_signature.corpus_expansion.corpus_expansion_manifest", "validate_corpus_expansion_bundle"),
    "validate_corpus_expansion_manifest": ("src.visual_signature.corpus_expansion.corpus_expansion_manifest", "validate_corpus_expansion_manifest"),
    "validate_corpus_expansion_manifest_payload": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "validate_corpus_expansion_manifest_payload",
    ),
    "validate_corpus_expansion_metrics": ("src.visual_signature.corpus_expansion.corpus_metrics", "validate_corpus_expansion_metrics"),
    "validate_corpus_expansion_metrics_payload": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "validate_corpus_expansion_metrics_payload",
    ),
    "validate_corpus_expansion_queue_item": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "validate_corpus_expansion_queue_item",
    ),
    "validate_corpus_expansion_readiness_payload": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "validate_corpus_expansion_readiness_payload",
    ),
    "validate_corpus_expansion_review_queue": (
        "src.visual_signature.corpus_expansion.corpus_review_queue",
        "validate_corpus_expansion_review_queue",
    ),
    "validate_corpus_expansion_review_queue_payload": (
        "src.visual_signature.corpus_expansion.corpus_expansion_models",
        "validate_corpus_expansion_review_queue_payload",
    ),
    "validate_reviewer_packets": ("src.visual_signature.corpus_expansion.reviewer_packets", "validate_reviewer_packets"),
    "validate_reviewer_workflow_pilot_payload": (
        "src.visual_signature.corpus_expansion.reviewer_workflow_pilot",
        "validate_reviewer_workflow_pilot_payload",
    ),
    "validate_reviewer_viewer_bundle": ("src.visual_signature.corpus_expansion.reviewer_viewer", "validate_reviewer_viewer_bundle"),
    "write_corpus_expansion_bundle": ("src.visual_signature.corpus_expansion.corpus_expansion_manifest", "write_corpus_expansion_bundle"),
    "write_reviewer_packets": ("src.visual_signature.corpus_expansion.reviewer_packets", "write_reviewer_packets"),
    "write_reviewer_workflow_pilot": ("src.visual_signature.corpus_expansion.reviewer_workflow_pilot", "write_reviewer_workflow_pilot"),
    "write_reviewer_viewer_bundle": ("src.visual_signature.corpus_expansion.reviewer_viewer", "write_reviewer_viewer_bundle"),
    "write_review_queue": ("src.visual_signature.corpus_expansion.corpus_review_queue", "write_review_queue"),
}

__getattr__ = make_lazy_getattr(globals(), _EXPORTS)
__dir__ = make_lazy_dir(globals(), _EXPORTS)
