"""Static local viewer for the Visual Signature reviewer workflow pilot."""

from __future__ import annotations

from src.visual_signature.corpus_expansion.reviewer_viewer_bundle import DEFAULT_CAPTURE_MANIFEST_PATH
from src.visual_signature.corpus_expansion.reviewer_viewer_bundle import DEFAULT_DISMISSAL_AUDIT_PATH
from src.visual_signature.corpus_expansion.reviewer_viewer_bundle import DEFAULT_OUTPUT_ROOT
from src.visual_signature.corpus_expansion.reviewer_viewer_bundle import DEFAULT_PACKETS_ROOT
from src.visual_signature.corpus_expansion.reviewer_viewer_bundle import DEFAULT_REVIEWER_WORKFLOW_PILOT_PATH
from src.visual_signature.corpus_expansion.reviewer_viewer_bundle import DEFAULT_REVIEW_QUEUE_PATH
from src.visual_signature.corpus_expansion.reviewer_viewer_bundle import REVIEWER_VIEWER_RECORD_TYPE
from src.visual_signature.corpus_expansion.reviewer_viewer_bundle import REVIEWER_VIEWER_SCHEMA_VERSION
from src.visual_signature.corpus_expansion.reviewer_viewer_bundle import build_reviewer_viewer_bundle
from src.visual_signature.corpus_expansion.reviewer_viewer_bundle import validate_reviewer_viewer_bundle
from src.visual_signature.corpus_expansion.reviewer_viewer_bundle import write_reviewer_viewer_bundle
from src.visual_signature.corpus_expansion.reviewer_viewer_render import _render_index_html
from src.visual_signature.corpus_expansion.reviewer_viewer_render import _viewer_css
from src.visual_signature.corpus_expansion.reviewer_viewer_render import _viewer_js
